[imaping]
filename = ima_ping.py
chunked = true
python.version = python3
local = true

[imaquery]
filename = ima_query.py
chunked = true
python.version = python3
local = true

[imaannotate]
filename = ima_annotate.py
chunked = true
python.version = python3
local = true

[imabuild]
filename = ima_build.py
chunked = true
python.version = python3
local = true

[imaaboutasset]
filename = ima_aboutasset.py
chunked = true
python.version = python3
local = true
