[ima_query]
filename = ima_query.py
generating = true
enableheader = true
outputheader = true
type = python
python.version = python3
local = true

[ima_annotate]
filename = ima_annotate.py
generating = true
enableheader = true
outputheader = true
type = python
python.version = python3
local = true

[ima_build]
filename = ima_build.py
generating = true
enableheader = true
outputheader = true
type = python
python.version = python3
local = true
